export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOAD_LEFTS_SUCCESS = 'LOAD_LEFTS_SUCCESS';
export const UPDATE_LEFT_SUCCESS = 'UPDATE_LEFT_SUCCESS';